### ISSUE TITLE
Accept lower-case versions for SRC blocks, etc.

### ISSUE THREAD

**Issue by AdamFrey** [eigenhombre/clj-org#3]
Hi!

Newer versions of Org mode since this commit (https://code.orgmode.org/bzg/org-mode/commit/13424336a6f30c50952d291e7a82906c1210daf0?style=split)  default to using lower-case versions of blocks `BEGIN_SRC -> begin_src`. Both versions are acceptable to Org, but this library only looks for uppercase versions. 

I know @eigenhombre that you aren't really using this library anymore, so if you are interested, I'd be willing to take over some maintenance duties for this library, as I use it in my blog generation. I'd rather help this library along vs forking and putting another artifact name out there.

**Comment by eigenhombre** [comment]
Would happily take a PR for this issue @AdamFrey ...

**Comment by garlic0x1** [comment]
> Would happily take a PR for this issue @AdamFrey ...

PR submitted

**Comment by eigenhombre** [comment]
Merged PR and added tests.

**Comment by eigenhombre** [comment]
This is on Clojars now as `clj-org 0.0.3`.
